# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(210, 20, 381, 481))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.datasetLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.datasetLabel.setObjectName("datasetLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.datasetLabel)
        self.datasetComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.datasetComboBox.setObjectName("datasetComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.datasetComboBox)
        self.categoryLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.categoryLabel.setObjectName("categoryLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.categoryLabel)
        self.categoryComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.categoryComboBox)
        self.countLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.countLabel.setObjectName("countLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.countLabel)
        self.countLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.countLineEdit.setObjectName("countLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.countLineEdit)
        self.faceNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.faceNameLabel.setObjectName("faceNameLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.faceNameLabel)
        self.faceNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.faceNameLineEdit.setObjectName("faceNameLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.faceNameLineEdit)
        self.add = QtWidgets.QPushButton(self.formLayoutWidget)
        self.add.setObjectName("add")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.add)
        self.epochsLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.epochsLabel.setObjectName("epochsLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.epochsLabel)
        self.epochsLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.epochsLineEdit.setObjectName("epochsLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.epochsLineEdit)
        self.train = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.train.sizePolicy().hasHeightForWidth())
        self.train.setSizePolicy(sizePolicy)
        self.train.setObjectName("train")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.train)
        self.evaluate = QtWidgets.QPushButton(self.formLayoutWidget)
        self.evaluate.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evaluate.sizePolicy().hasHeightForWidth())
        self.evaluate.setSizePolicy(sizePolicy)
        self.evaluate.setObjectName("evaluate")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.evaluate)
        self.progressBar = QtWidgets.QProgressBar(self.formLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.datasetLabel.setText(_translate("MainWindow", "Dataset"))
        self.categoryLabel.setText(_translate("MainWindow", "Category"))
        self.countLabel.setText(_translate("MainWindow", "Count"))
        self.faceNameLabel.setText(_translate("MainWindow", "Face Name"))
        self.add.setText(_translate("MainWindow", "Add"))
        self.epochsLabel.setText(_translate("MainWindow", "Epochs"))
        self.train.setText(_translate("MainWindow", "Train"))
        self.evaluate.setText(_translate("MainWindow", "Evaluate"))

